routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');

Auth::routes();

//bank search via select2
Route::get('bank-autocomplete-search','BankAccountController@autoCompleteSearch')->name('bank-autocomplete-search');

Route::group(['middleware' => ['auth']], function() {
	//change password
	Route::get('change-password','HomeController@showChangePasswordForm');
	Route::post('change-password','HomeController@changePassword');
});
Route::get('/home', 'HomeController@index')->name('home');

//only super admin routes
Route::group(['middleware' => ['role:super_admin']], function() {
	//personal transactions serverside data table processing
	Route::post('all-personal-transactions', 'PersonalTransactionController@allTransactions');
	//personal indices serverside data table processing
	Route::post('all-indices', 'IndexController@allIndices');
	Route::post('all-prayers', 'PrayerController@allPrayers');
	//company report
	Route::get('company/report/{id}', 'CompanyController@returnDatePage');
	Route::post('company/report/by-date/{id}', 'CompanyController@report')->name('company.report');
	//loan report
	Route::get('loan/report/{id}', 'LoanController@report')->name('loan.report');
	//loan transactions serverside data table processing
	Route::post('all-loan-transactions', 'LoanTransactionController@allTransactions');
	//resource routes
	Route::resource('company', 'CompanyController');
	Route::resource('loan', 'LoanController');
	Route::resource('loan-transaction', 'LoanTransactionController');
	Route::resource('personal-transaction', 'PersonalTransactionController');
	Route::resource('index', 'IndexController');
	Route::resource('cc-loan', 'CcLoanController');
	Route::resource('cc-loan-withdraw', 'CcLoanWithdrawController');
	Route::resource('cc-loan-deposit', 'CcLoanDepositController');
	Route::resource('prayer', 'PrayerController');

});



//regular business routes
Route::group(['prefix' => 'business', 'as' => 'business.', 'middleware' => ['role:super_admin|business_admin']], function() {

	//server side processing of data tables
	//suppliers
	Route::post('all-suppliers', 'Business\SupplierController@allSuppliers');
	//customers
	Route::post('all-customers', 'Business\CustomerController@allCustomers');
	//expenses for super admin
	Route::post('all-expenses', 'Business\ExpenseController@allExpenses');
	//expense datatable view for business admin
	Route::post('admin/all-expenses', 'Business\ExpenseController@allExpensesAdminView');
	//expenses for business admin
	Route::post('admin/all-expenses/{id}', 'Business\ExpenseItemController@particularExpenseAdminView');
	//all expenses of a particular item
	Route::post('all-expenses/{id}', 'Business\ExpenseItemController@particularExpense');
	//expense payments for super admin
	Route::post('all-expense-transactions/{id}', 'Business\ExpenseItemController@particularPayment');
	//expense payments for business admin
	Route::post('admin/all-expense-transactions/{id}', 'Business\ExpenseItemController@particularPaymentAdminView');
	//purchases for super admin
	Route::post('all-purchases', 'Business\PurchaseController@allPurchases');
	//purchases for business admin
	Route::post('admin/all-purchases', 'Business\PurchaseController@allPurchasesAdminView');
	//purchase-deliveries for super admin
	Route::post('all-purchase-deliveries', 'Business\PurchaseDeliveryController@allPurchaseDeliveries');
	//purchase-deliveries for business admin
	Route::post('admin/all-purchase-deliveries', 'Business\PurchaseDeliveryController@allPurchaseDeliveriesAdminView');
	//sale-deliveries for super admin
	Route::post('all-sale-deliveries', 'Business\SaleDeliveryController@allSaleDeliveries');
	//sale-deliveries for business admin
	Route::post('admin/all-sale-deliveries', 'Business\SaleDeliveryController@allSaleDeliveriesAdminView');
	//wastage datatable view for suprer admin
	Route::post('all-wastages', 'Business\ProductWastageController@allWastages');
	//wastage datatable view for business admin
	Route::post('admin/all-wastages', 'Business\ProductWastageController@allWastagesAdminView');
	//purchase order datatable view for suprer admin
	Route::post('all-purchase-orders', 'Business\PurchaseOrderController@allOrders');
	//purchase order datatable view for business admin
	Route::post('admin/all-purchase-orders', 'Business\PurchaseOrderController@allOrdersAdminView');
	//sale order datatable view for suprer admin
	Route::post('all-sale-orders', 'Business\SaleOrderController@allOrders');
	//sale order datatable view for business admin
	Route::post('admin/all-sale-orders', 'Business\SaleOrderController@allOrdersAdminView');
	//purchase transactions datatable view for suprer admin
	Route::post('all-purchase-transactions', 'Business\PurchaseTransactionController@allTransactions');
	//purchase order datatable view for business admin
	Route::post('admin/all-purchase-transactions', 'Business\PurchaseTransactionController@allTransactionsAdminView');
	//expense transactions datatable view for suprer admin
	Route::post('all-expense-transactions', 'Business\ExpenseTransactionController@allTransactions');
	//expense payments datatable view for business admin
	Route::post('admin/all-expense-transactions', 'Business\ExpenseTransactionController@allTransactionsAdminView');
	//sale transactions datatable view for suprer admin
	Route::post('all-sale-transactions', 'Business\SaleTransactionController@allTransactions');
	//sale order datatable view for business admin
	Route::post('admin/all-sale-transactions', 'Business\SaleTransactionController@allTransactionsAdminView');
	//sale transactions datatable view for suprer admin
	Route::post('all-sale-payment-returns', 'Business\SalePaymentReturnController@allTransactions');
	//sale order datatable view for business admin
	Route::post('admin/all-sale-payment-returns', 'Business\SalePaymentReturnController@allTransactionsAdminView');
	//sale transactions datatable view for suprer admin
	Route::post('all-purchase-payment-returns', 'Business\PurchasePaymentReturnController@allTransactions');
	//purchase order datatable view for business admin
	Route::post('admin/all-purchase-payment-returns', 'Business\PurchasePaymentReturnController@allTransactionsAdminView');
	//bank transactions datatable view for suprer admin
	Route::post('all-bank-transactions', 'Business\BankAccountTransactionController@allTransactions');
	//bank order datatable view for business admin
	Route::post('admin/all-bank-transactions', 'Business\BankAccountTransactionController@allTransactionsAdminView');
	//sales for super admin
	Route::post('all-sales', 'Business\SaleController@allSales');
	//sales for business admin
	Route::post('admin/all-sales', 'Business\SaleController@allSalesAdminView');

	//customer report
	Route::get('customer/report/{id}', 'Business\CustomerController@returnDatePage')->name('customer.report');
	Route::post('customer/report', 'Business\CustomerController@report');
	Route::post('customer/report/print', 'Business\CustomerController@printReport');
	Route::post('customer/report/pdf', 'Business\CustomerController@reportExportPDF');
	Route::post('customer/report/excel', 'Business\CustomerController@reportExportExcel');

	//supplier report
	Route::get('supplier/report/{id}', 'Business\SupplierController@returnDatePage')->name('supplier.report');
	Route::post('supplier/report', 'Business\SupplierController@report');
	Route::post('supplier/report/print', 'Business\SupplierController@printReport');
	Route::post('supplier/report/pdf', 'Business\SupplierController@reportExportPDF');
	Route::post('supplier/report/excel', 'Business\SupplierController@reportExportExcel');

	//purchase report
	Route::post('purchase/report', 'Business\PurchaseController@report')->name('purchase.report');
	Route::post('purchase/report/print', 'Business\PurchaseController@printReport');
	Route::post('purchase/report/pdf', 'Business\PurchaseController@reportExportPDF');
	Route::post('purchase/report/excel', 'Business\PurchaseController@reportExportExcel');

	//purchase transaction report
	Route::post('purchase-transaction/report', 'Business\PurchaseTransactionController@report');
	Route::post('purchase-transaction/report/print', 'Business\PurchaseTransactionController@printReport');
	Route::post('purchase-transaction/report/pdf', 'Business\PurchaseTransactionController@reportExportPDF');
	Route::post('purchase-transaction/report/excel', 'Business\PurchaseTransactionController@reportExportExcel');

	//purchase payment report
	Route::post('purchase-payment-return/report', 'Business\PurchasePaymentReturnController@report');
	Route::post('purchase-payment-return/report/print', 'Business\PurchasePaymentReturnController@printReport');
	Route::post('purchase-payment-return/report/pdf', 'Business\PurchasePaymentReturnController@reportExportPDF');
	Route::post('purchase-payment-return/report/excel', 'Business\PurchasePaymentReturnController@reportExportExcel');

	//sale report
	Route::post('sale/report', 'Business\SaleController@report')->name('sale.report');
	Route::post('sale/report/print', 'Business\SaleController@printReport');
	Route::post('sale/report/pdf', 'Business\SaleController@reportExportPDF');
	Route::post('sale/report/excel', 'Business\SaleController@reportExportExcel');

	//sale invoice/bill menu
	Route::get('sale/invoice', 'Business\SaleController@returnViewPage');
	Route::post('sale/invoice', 'Business\SaleController@invoice');
	Route::post('sale/invoice/print', 'Business\SaleController@invoicePrint');

app/Http/Controllers/PersonalTransactionController.php
<?php

namespace App\Http\Controllers;

use App\PersonalTransaction;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class PersonalTransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    	$income = PersonalTransaction::where('purpose','=','1')->sum('amount');
    	$expense = PersonalTransaction::where('purpose','=','2')->sum('amount');
        return view('pages.personal-transaction.index',compact('income','expense'));
    }

    //server side datatable super admin view
    public function allTransactions(Request $request)
    {     
        $columns = array( 
                            0 => 'id', 
                            1 => 'date',
                            2 => 'purpose',
                            3 => 'amount',
                            4 => 'received_from',
                            5 => 'expense_for',
                            6 => 'details',
                            7 => 'actions',
                        );
        

        $totalData = PersonalTransaction::count();
        $totalFiltered = $totalData; 

        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');
            
        if(empty($request->input('search.value')))
        {

            $transactions = PersonalTransaction::offset($start)
                    ->limit($limit)
                    ->orderBy($order,$dir)
                    ->get();

        }
        else {
            $search = $request->input('search.value'); 

            $transactions =  PersonalTransaction::where('amount','LIKE',"%{$search}%")
                        ->orWhere('date','LIKE',"%{$search}%")
                        ->orWhere('expense_for','LIKE',"%{$search}%")
                        ->orWhere('received_from','LIKE',"%{$search}%")
                        ->offset($start)
                        ->limit($limit)
                        ->orderBy($order,$dir)
                        ->get();

            $totalFiltered = PersonalTransaction::where('amount','LIKE',"%{$search}%")
                        ->orWhere('date','LIKE',"%{$search}%")
                        ->orWhere('expense_for','LIKE',"%{$search}%")
                        ->orWhere('received_from','LIKE',"%{$search}%")
                        ->count();
        }

        $data = array();
        if(!empty($transactions))
        {
            foreach ($transactions as $key => $value)
            {
                $nestedData['id'] = $key + 1;
                $nestedData['date'] = $value->date->format("d-m-Y");
                if ($value->purpose == 1) {
                    $nestedData['purpose'] = 'Income';
                }
                else {
                    $nestedData['purpose'] = 'Expense';
                }
                $nestedData['amount'] = $value->amount;
                $nestedData['received_from'] = $value->received_from;
                $nestedData['expense_for'] = $value->expense_for;
                $nestedData['details'] = $value->details;
                $nestedData['actions'] = '<div class="btn-group">
                                    <a href="'.route('personal-transaction.show',$value->id) .'" class="btn btn-secondary btn-sm" title="Show">
                                        Show
                                    </a>
                                    <a href="'.route('personal-transaction.edit',$value->id) .'" class="btn btn-success btn-sm" title="Update">
                                        Update
                                    </a>
                                    <button class="btn btn-sm btn-danger btn-delete" data-remote=" '.route('personal-transaction.destroy',$value->id) .'" title="Delete">Delete</button>
                                </div>';
                $data[] = $nestedData;
            }
        }
          
        $json_data = array(
                    "draw"            => intval($request->input('draw')),  
                    "recordsTotal"    => intval($totalData),  
                    "recordsFiltered" => intval($totalFiltered), 
                    "data"            => $data,   
                    );
            
        echo json_encode($json_data);        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $personalTransaction = null;
        return view('pages.personal-transaction.create', compact('personalTransaction'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'date'      => 'required',
            'purpose'  => ['required', Rule::notIn(['','0'])],
            'amount'    => 'required|numeric',
        ]);

        PersonalTransaction::create($request->all());

        return redirect()
                    ->route('personal-transaction.index')
                    ->with('success', 'Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PersonalTransaction  $personalTransaction
     * @return \Illuminate\Http\Response
     */
    public function show(PersonalTransaction $personalTransaction)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PersonalTransaction  $personalTransaction
     * @return \Illuminate\Http\Response
     */
    public function edit(PersonalTransaction $personalTransaction)
    {
        return view('pages.personal-transaction.edit', compact('personalTransaction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PersonalTransaction  $personalTransaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PersonalTransaction $personalTransaction)
    {
        $request->validate([
            'date'      => 'required',
            'purpose'  => ['required', Rule::notIn(['','0'])],
            'amount'    => 'required|numeric',
        ]);

        $personalTransaction->update($request->all());

        return redirect()
                    ->route('personal-transaction.index')
                    ->with('success','Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PersonalTransaction  $personalTransaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(PersonalTransaction $personalTransaction)
    {
        $personalTransaction->delete();

        return redirect()
                    ->route('personal-transaction.index')
                    ->with('success','Deleted Successfully');
    }
}

resources/views/pages/personal-transaction/create.blade.php
@extends('layouts.master')
@section('title', 'Personal Transaction')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Add New Transaction</h1>
				</div><!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
						<li class="breadcrumb-item"><a href="{{ url('index') }}">Personal Account</a></li>
						<li class="breadcrumb-item active">Create</li>
					</ol>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="card card-warning">
				<div class="card-body">
					<form method="POST" action="{{ route('personal-transaction.store') }}">
						@csrf
						@include('pages.personal-transaction.form')
						
					</form>
				</div>
			</div>
		</div>
	</section>
</div>
@endsection

resources/views/pages/personal-transaction/edit.blade.php
@extends('layouts.master')
@section('title', 'Personal Account')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Update Transaction</h1>
				</div><!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
						<li class="breadcrumb-item"><a href="{{ url('index') }}">Personal Account</a></li>
						<li class="breadcrumb-item active">Update</li>
					</ol>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="card card-warning">
				<div class="card-body">
					<form method="POST" action="{{ route('personal-transaction.update', $personalTransaction->id) }}">
						@csrf
						@method('PUT')

						@include('pages.personal-transaction.form')
					</form>
				</div>
			</div>
		</div>
	</section>
</div>
@endsection

resources/views/pages/personal-transaction/form.blade.php
{{-- Date --}}
<div class="form-group">
	<label for="date">
		Date
	</label>

	<input type="text" class="form-control{{ $errors->has('date') ? ' is-invalid' : '' }}" name="date" id="date" value="{{ old('date', optional($personalTransaction)->date) }}">

	@if ($errors->has('date'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('date') }}</strong>
	</span>
	@endif
</div>

{{-- Supplier --}}
<div class="form-group">
	<label for="purpose">Select Purpose</label>
	<select name="purpose" class="form-control{{ $errors->has('purpose') ? ' is-invalid' : '' }}" id="purpose">
		<option value="">Select</option>
		<option value="1" {{old('purpose', optional($personalTransaction)->purpose) =='1' ? 'selected':''}}>Income</option>
		<option value="2" {{old('purpose', optional($personalTransaction)->purpose) =='2' ? 'selected':''}}>Expense</option>
	</select>
	@if ($errors->has('purpose'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('purpose') }}</strong>
	</span>
	@endif
</div>

<div id="income_div">
	{{-- received_from --}}
	<div class="form-group">
		<label for="received_from">
			Received From
		</label>

		<input type="text" class="form-control{{ $errors->has('received_from') ? ' is-invalid' : '' }}" name="received_from" id="received_from" value="{{ old('received_from', optional($personalTransaction)->received_from) }}">

		@if ($errors->has('received_from'))
		<span class="invalid-feedback">
			<strong>{{ $errors->first('received_from') }}</strong>
		</span>
		@endif
	</div>
</div>

<div id="expense_div">
	{{-- expense_for --}}
	<div class="form-group">
		<label for="expense_for">Expense For</label>
		<input type="text" class="form-control{{ $errors->has('expense_for') ? ' is-invalid' : '' }}" name="expense_for" id="expense_for" value="{{ old('expense_for', optional($personalTransaction)->expense_for) }}">

		@if ($errors->has('expense_for'))
		<span class="invalid-feedback">
			<strong>{{ $errors->first('expense_for') }}</strong>
		</span>
		@endif
	</div>
</div>

{{-- name --}}
<div class="form-group">
	<label for="amount">
		Amount
	</label>

	<input type="text" class="form-control{{ $errors->has('amount') ? ' is-invalid' : '' }}" name="amount" id="amount" value="{{ old('amount', optional($personalTransaction)->amount) }}">

	@if ($errors->has('amount'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('amount') }}</strong>
	</span>
	@endif
</div>

{{-- details --}}
<div class="form-group">
	<label for="details">Remarks</label>
	<textarea name="details" class="form-control {{ $errors->has('details') ? ' is-invalid' : '' }}" id="details" cols="30" rows="5">{{ old('details', optional($personalTransaction)->details) }}</textarea>

	@if ($errors->has('details'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('details') }}</strong>
	</span>
	@endif
</div>

{{-- Save --}}
<div class="form-group row mb-0">
	<div class="col-md-12">
		<button type="submit" class="btn btn-primary">
			{{ __('Save') }}
		</button>
	</div>
</div>

@section('script')
<script>
	$( function() {
		$( "#date" ).datepicker({
			dateFormat: 'yy-mm-dd',
			changeMonth: true,
			changeYear: true,
		});
	});
	//show or hide banking and mobile banking section on page load
	$(document).ready(function(){
		var type = $('#purpose').val();
		if (type == 1) {
			$('#expense_div').hide();
			$('#income_div').show();
		}

		else if (type == 2) {
			$('#income_div').hide();
			$('#expense_div').show();
		}
		else{
			$('#income_div').hide();
			$('#expense_div').hide();
		}
	});

	$('#purpose').on('change', function(){
		var type = $('#purpose').val();
		if (type == 1) {
			$('#expense_div').hide();
			$('#income_div').show();
		}

		else if (type == 2) {
			$('#income_div').hide();
			$('#expense_div').show();
		}
		else{
			$('#income_div').hide();
			$('#expense_div').hide();
		}
	});
</script>
@endsection

resources/views/pages/personal-transaction/index.blade.php
@extends('layouts.master')
@section('title', 'Personal Transactions')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Personal Transactions</h1>
				</div><!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
						<li class="breadcrumb-item active">Personal Transactions</li>
					</ol>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="card">
				<div class="card-header">
					<h6>Income: {{ $income }}</h6>
					<h6>Expense: {{ $expense }}</h6>
					<h6>Balance: {{ $income - $expense }}</h6>
				</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
							<thead>
								<tr>
									<th>SL</th>
									<th>Date</th>									
									<th>Purpose</th>								
									<th>Amount</th>							
									<th>Received From</th>
									<th>Expense For</th>
									<th>Remarks</th>
									<th>Action</th>
								</tr>
							</thead>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
@endsection

@section('script')
<script>
	//server side data table
	$(document).ready(function () {
		$('#dataTable').DataTable({
			"order": [[ 1, "desc" ]],
			"processing": true,
			"serverSide": true,
			"ajax":{
				"url": "{{ url('all-personal-transactions') }}",
				"dataType": "json",
				"type": "POST",
				"data":{ _token: "{{ csrf_token() }}"}
			},
			"columns": [
			{ "data": "id" },
			{ "data": "date" },
			{ "data": "purpose" },
			{ "data": "amount" },
			{ "data": "received_from" },
			{ "data": "expense_for" },
			{ "data": "details" },
			{ "data": "actions" }
			],	 
		});
	});

    //delete a row using ajax
    $('#dataTable').on('click', '.btn-delete[data-remote]', function (e) { 
    	e.preventDefault();
    	$.ajaxSetup({
    		headers: {
    			'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    		}
    	});
    	var url = $(this).data('remote');
        // confirm then
        if (confirm('are you sure you want to delete this?')) {
        	$.ajax({
        		url: url,
        		type: 'POST',
        		dataType: 'json',
        		data: {_method: 'DELETE', submit: true}
        	}).always(function (data) {
        		$('#dataTable').DataTable().draw(false);
        	});
        }
    });
</script>
@endsection