routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');

Auth::routes();

//bank search via select2
Route::get('bank-autocomplete-search','BankAccountController@autoCompleteSearch')->name('bank-autocomplete-search');

Route::group(['middleware' => ['auth']], function() {
	//change password
	Route::get('change-password','HomeController@showChangePasswordForm');
	Route::post('change-password','HomeController@changePassword');
});
Route::get('/home', 'HomeController@index')->name('home');

//only super admin routes
Route::group(['middleware' => ['role:super_admin']], function() {
	//personal transactions serverside data table processing
	Route::post('all-personal-transactions', 'PersonalTransactionController@allTransactions');
	//personal indices serverside data table processing
	Route::post('all-indices', 'IndexController@allIndices');
	Route::post('all-prayers', 'PrayerController@allPrayers');
	//company report
	Route::get('company/report/{id}', 'CompanyController@returnDatePage');
	Route::post('company/report/by-date/{id}', 'CompanyController@report')->name('company.report');
	//loan report
	Route::get('loan/report/{id}', 'LoanController@report')->name('loan.report');
	//loan transactions serverside data table processing
	Route::post('all-loan-transactions', 'LoanTransactionController@allTransactions');
	//resource routes
	Route::resource('company', 'CompanyController');
	Route::resource('loan', 'LoanController');
	Route::resource('loan-transaction', 'LoanTransactionController');
	Route::resource('personal-transaction', 'PersonalTransactionController');
	Route::resource('index', 'IndexController');
	Route::resource('cc-loan', 'CcLoanController');
	Route::resource('cc-loan-withdraw', 'CcLoanWithdrawController');
	Route::resource('cc-loan-deposit', 'CcLoanDepositController');
	Route::resource('prayer', 'PrayerController');

});



//regular business routes
Route::group(['prefix' => 'business', 'as' => 'business.', 'middleware' => ['role:super_admin|business_admin']], function() {

	//server side processing of data tables
	//suppliers
	Route::post('all-suppliers', 'Business\SupplierController@allSuppliers');
	//customers
	Route::post('all-customers', 'Business\CustomerController@allCustomers');
	//expenses for super admin
	Route::post('all-expenses', 'Business\ExpenseController@allExpenses');
	//expense datatable view for business admin
	Route::post('admin/all-expenses', 'Business\ExpenseController@allExpensesAdminView');
	//expenses for business admin
	Route::post('admin/all-expenses/{id}', 'Business\ExpenseItemController@particularExpenseAdminView');
	//all expenses of a particular item
	Route::post('all-expenses/{id}', 'Business\ExpenseItemController@particularExpense');
	//expense payments for super admin
	Route::post('all-expense-transactions/{id}', 'Business\ExpenseItemController@particularPayment');
	//expense payments for business admin
	Route::post('admin/all-expense-transactions/{id}', 'Business\ExpenseItemController@particularPaymentAdminView');
	//purchases for super admin
	Route::post('all-purchases', 'Business\PurchaseController@allPurchases');
	//purchases for business admin
	Route::post('admin/all-purchases', 'Business\PurchaseController@allPurchasesAdminView');
	//purchase-deliveries for super admin
	Route::post('all-purchase-deliveries', 'Business\PurchaseDeliveryController@allPurchaseDeliveries');
	//purchase-deliveries for business admin
	Route::post('admin/all-purchase-deliveries', 'Business\PurchaseDeliveryController@allPurchaseDeliveriesAdminView');
	//sale-deliveries for super admin
	Route::post('all-sale-deliveries', 'Business\SaleDeliveryController@allSaleDeliveries');
	//sale-deliveries for business admin
	Route::post('admin/all-sale-deliveries', 'Business\SaleDeliveryController@allSaleDeliveriesAdminView');
	//wastage datatable view for suprer admin
	Route::post('all-wastages', 'Business\ProductWastageController@allWastages');
	//wastage datatable view for business admin
	Route::post('admin/all-wastages', 'Business\ProductWastageController@allWastagesAdminView');
	//purchase order datatable view for suprer admin
	Route::post('all-purchase-orders', 'Business\PurchaseOrderController@allOrders');
	//purchase order datatable view for business admin
	Route::post('admin/all-purchase-orders', 'Business\PurchaseOrderController@allOrdersAdminView');
	//sale order datatable view for suprer admin
	Route::post('all-sale-orders', 'Business\SaleOrderController@allOrders');
	//sale order datatable view for business admin
	Route::post('admin/all-sale-orders', 'Business\SaleOrderController@allOrdersAdminView');
	//purchase transactions datatable view for suprer admin
	Route::post('all-purchase-transactions', 'Business\PurchaseTransactionController@allTransactions');
	//purchase order datatable view for business admin
	Route::post('admin/all-purchase-transactions', 'Business\PurchaseTransactionController@allTransactionsAdminView');
	//expense transactions datatable view for suprer admin
	Route::post('all-expense-transactions', 'Business\ExpenseTransactionController@allTransactions');
	//expense payments datatable view for business admin
	Route::post('admin/all-expense-transactions', 'Business\ExpenseTransactionController@allTransactionsAdminView');
	//sale transactions datatable view for suprer admin
	Route::post('all-sale-transactions', 'Business\SaleTransactionController@allTransactions');
	//sale order datatable view for business admin
	Route::post('admin/all-sale-transactions', 'Business\SaleTransactionController@allTransactionsAdminView');
	//sale transactions datatable view for suprer admin
	Route::post('all-sale-payment-returns', 'Business\SalePaymentReturnController@allTransactions');
	//sale order datatable view for business admin
	Route::post('admin/all-sale-payment-returns', 'Business\SalePaymentReturnController@allTransactionsAdminView');
	//sale transactions datatable view for suprer admin
	Route::post('all-purchase-payment-returns', 'Business\PurchasePaymentReturnController@allTransactions');
	//purchase order datatable view for business admin
	Route::post('admin/all-purchase-payment-returns', 'Business\PurchasePaymentReturnController@allTransactionsAdminView');
	//bank transactions datatable view for suprer admin
	Route::post('all-bank-transactions', 'Business\BankAccountTransactionController@allTransactions');
	//bank order datatable view for business admin
	Route::post('admin/all-bank-transactions', 'Business\BankAccountTransactionController@allTransactionsAdminView');
	//sales for super admin
	Route::post('all-sales', 'Business\SaleController@allSales');
	//sales for business admin
	Route::post('admin/all-sales', 'Business\SaleController@allSalesAdminView');

	//customer report
	Route::get('customer/report/{id}', 'Business\CustomerController@returnDatePage')->name('customer.report');
	Route::post('customer/report', 'Business\CustomerController@report');
	Route::post('customer/report/print', 'Business\CustomerController@printReport');
	Route::post('customer/report/pdf', 'Business\CustomerController@reportExportPDF');
	Route::post('customer/report/excel', 'Business\CustomerController@reportExportExcel');

	//supplier report
	Route::get('supplier/report/{id}', 'Business\SupplierController@returnDatePage')->name('supplier.report');
	Route::post('supplier/report', 'Business\SupplierController@report');
	Route::post('supplier/report/print', 'Business\SupplierController@printReport');
	Route::post('supplier/report/pdf', 'Business\SupplierController@reportExportPDF');
	Route::post('supplier/report/excel', 'Business\SupplierController@reportExportExcel');

	//purchase report
	Route::post('purchase/report', 'Business\PurchaseController@report')->name('purchase.report');
	Route::post('purchase/report/print', 'Business\PurchaseController@printReport');
	Route::post('purchase/report/pdf', 'Business\PurchaseController@reportExportPDF');
	Route::post('purchase/report/excel', 'Business\PurchaseController@reportExportExcel');

	//purchase transaction report
	Route::post('purchase-transaction/report', 'Business\PurchaseTransactionController@report');
	Route::post('purchase-transaction/report/print', 'Business\PurchaseTransactionController@printReport');
	Route::post('purchase-transaction/report/pdf', 'Business\PurchaseTransactionController@reportExportPDF');
	Route::post('purchase-transaction/report/excel', 'Business\PurchaseTransactionController@reportExportExcel');

	//purchase payment report
	Route::post('purchase-payment-return/report', 'Business\PurchasePaymentReturnController@report');
	Route::post('purchase-payment-return/report/print', 'Business\PurchasePaymentReturnController@printReport');
	Route::post('purchase-payment-return/report/pdf', 'Business\PurchasePaymentReturnController@reportExportPDF');
	Route::post('purchase-payment-return/report/excel', 'Business\PurchasePaymentReturnController@reportExportExcel');

	//sale report
	Route::post('sale/report', 'Business\SaleController@report')->name('sale.report');
	Route::post('sale/report/print', 'Business\SaleController@printReport');
	Route::post('sale/report/pdf', 'Business\SaleController@reportExportPDF');
	Route::post('sale/report/excel', 'Business\SaleController@reportExportExcel');

	//sale invoice/bill menu
	Route::get('sale/invoice', 'Business\SaleController@returnViewPage');
	Route::post('sale/invoice', 'Business\SaleController@invoice');
	Route::post('sale/invoice/print', 'Business\SaleController@invoicePrint');

app/CcLoanDeposit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\CcLoan;

class CcLoanDeposit extends Model
{
    use SoftDeletes;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at','deposit_date','withdraw_date'];

    public function loan(){
    	return $this->belongsTo(CcLoan::class, 'loan_id')->withTrashed();
    }
}

app/Http/Controllers/CcLoanDepositController.php
<?php

namespace App\Http\Controllers;

use App\CcLoanDeposit;
use App\CcLoan;
use Illuminate\Http\Request;
use DB;

class CcLoanDepositController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $deposits = CcLoanDeposit::latest()->get();
        return view('pages.cc-loan-deposit.index',compact('deposits'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ccLoans = CcLoan::all();
        $ccLoanDeposit = null;
        return view('pages.cc-loan-deposit.create', compact('ccLoans','ccLoanDeposit'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'loan_id'  =>'required',
            'amount'      => 'required|numeric',
            'interest'      => 'required|numeric',
            'interest_rate'      => 'required|numeric',
            'withdraw_date'      => 'required',
            'deposit_date'      => 'required',
        ]);
        DB::transaction(function () use ($request) {
            CcLoanDeposit::create($request->all());
            $ccLoan = CcLoan::find($request->loan_id);
            $ccLoan->available = $ccLoan->available + $request->amount;
            $ccLoan->save();
        });
        return redirect()
                    ->route('cc-loan-deposit.index')
                    ->with('success', 'Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\CcLoanDeposit  $ccLoanDeposit
     * @return \Illuminate\Http\Response
     */
    public function show(CcLoanDeposit $ccLoanDeposit)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\CcLoanDeposit  $ccLoanDeposit
     * @return \Illuminate\Http\Response
     */
    public function edit(CcLoanDeposit $ccLoanDeposit)
    {
        $ccLoans = CcLoan::all();
        return view('pages.cc-loan-deposit.edit', compact('ccLoans','ccLoanDeposit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\CcLoanDeposit  $ccLoanDeposit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CcLoanDeposit $ccLoanDeposit)
    {
        $request->validate([
            'loan_id'  =>'required',
            'amount'      => 'required|numeric',
            'interest'      => 'required|numeric',
            'interest_rate'      => 'required|numeric',
            'withdraw_date'      => 'required',
            'deposit_date'      => 'required',
        ]);

        DB::transaction(function () use ($request, $ccLoanDeposit) {
            //CcLoanWithdraw::create($request->all());
            $ccLoan = CcLoan::find($ccLoanDeposit->loan_id);
            $ccLoan->available = $ccLoan->available - $ccLoanDeposit->amount;
            $ccLoan->save();

            $ccLoanDeposit->update($request->all());

            $newCcLoan = CcLoan::find($request->loan_id);
            $newCcLoan->available = $newCcLoan->available + $request->amount;
            $newCcLoan->save();
        });
        return redirect()
                    ->route('cc-loan-deposit.index')
                    ->with('success', 'Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\CcLoanDeposit  $ccLoanDeposit
     * @return \Illuminate\Http\Response
     */
    public function destroy(CcLoanDeposit $ccLoanDeposit)
    {
        DB::transaction(function () use ($ccLoanDeposit) {
            //CcLoanDeposit::create($request->all());
            $ccLoan = CcLoan::find($ccLoanDeposit->loan_id);
            $ccLoan->available = $ccLoan->available - $ccLoanDeposit->amount;
            $ccLoan->save();

            $ccLoanDeposit->delete();
        });
        return redirect()
                    ->route('cc-loan-deposit.index')
                    ->with('success', 'Deleted Successfully');
    }
}

resources/views/pages/cc-loan-deposit/create.blade.php
@extends('layouts.master')
@section('title', 'CC Loan')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Add Deposit</h1>
				</div><!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
						<li class="breadcrumb-item"><a href="{{ url('cc-loan') }}">Loans</a></li>
						<li class="breadcrumb-item active">Deposit</li>
					</ol>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="card card-warning">
				<div class="card-body">
					<form method="POST" action="{{ route('cc-loan-deposit.store') }}">
						@csrf
						@include('pages.cc-loan-deposit.form')
						
					</form>
				</div>
			</div>
		</div>
	</section>
</div>
@endsection

resources/views/pages/cc-loan-deposit/edit.blade.php
@extends('layouts.master')
@section('title', 'CC Loan')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Edit Deposit</h1>
				</div><!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
						<li class="breadcrumb-item"><a href="{{ url('cc-loan') }}">Loans</a></li>
						<li class="breadcrumb-item active">Deposit</li>
					</ol>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="card card-warning">
				<div class="card-body">
					<form method="POST" action="{{ route('cc-loan-deposit.update', $ccLoanDeposit->id) }}">
						@csrf
						@method('PUT')
						@include('pages.cc-loan-deposit.form')
						
					</form>
				</div>
			</div>
		</div>
	</section>
</div>
@endsection

resources/views/pages/cc-loan-deposit/form.blade.php
{{-- Date --}}
<div class="form-group">
	<label for="withdraw_date">
		Withdraw Date
	</label>

	<input type="text" class="form-control{{ $errors->has('withdraw_date') ? ' is-invalid' : '' }}" name="withdraw_date" id="withdraw_date" value="{{ old('withdraw_date', optional($ccLoanDeposit)->withdraw_date) }}">

	@if ($errors->has('withdraw_date'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('withdraw_date') }}</strong>
	</span>
	@endif
</div>

<div class="form-group">
	<label for="deposit_date">
		Deposit Date
	</label>

	<input type="text" class="form-control{{ $errors->has('deposit_date') ? ' is-invalid' : '' }}" name="deposit_date" id="deposit_date" value="{{ old('deposit_date', optional($ccLoanDeposit)->deposit_date) }}">

	@if ($errors->has('deposit_date'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('deposit_date') }}</strong>
	</span>
	@endif
</div>

{{-- Loan --}}
<div class="form-group">
	<label for="loan_id">Select Loan</label>
	<select name="loan_id" class="form-control{{ $errors->has('loan_id') ? ' is-invalid' : '' }}" id="loan_id">
		<option value="">Select Loan</option>
		@forelse($ccLoans as $loan)
		<option value="{{ $loan->id }}" 
			@if( old('loan_id', optional($ccLoanDeposit)->loan_id) == $loan->id )
			selected
			@endif
			>
			{{ $loan->loan_from.', '.$loan->limit }}
		</option>
		@empty
		<option value="">No Loan Found</option>
		@endforelse
	</select>
	@if ($errors->has('loan_id'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('loan_id') }}</strong>
	</span>
	@endif
</div>

{{-- Amount --}}
<div class="form-group">
	<label for="amount">
		Amount
	</label>

	<input type="number" min="0" step="any" class="form-control{{ $errors->has('amount') ? ' is-invalid' : '' }}" name="amount" id="amount" value="{{ old('amount', optional($ccLoanDeposit)->amount) }}">

	@if ($errors->has('amount'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('amount') }}</strong>
	</span>
	@endif
</div>

{{-- Amount --}}
<div class="form-group">
	<label for="interest_rate">
		Profit Rate
	</label>

	<input type="number" min="0" step="any" class="form-control{{ $errors->has('interest_rate') ? ' is-invalid' : '' }}" name="interest_rate" id="interest_rate" value="{{ old('interest_rate', optional($ccLoanDeposit)->interest_rate) }}">

	@if ($errors->has('interest_rate'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('interest_rate') }}</strong>
	</span>
	@endif
</div>

{{-- Amount --}}
<div class="form-group">
	<label for="interest">
		Profit
	</label>

	<input type="number" min="0" step="any" class="form-control{{ $errors->has('interest') ? ' is-invalid' : '' }}" name="interest" id="interest" value="{{ old('interest', optional($ccLoanDeposit)->interest) }}">

	@if ($errors->has('interest'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('interest') }}</strong>
	</span>
	@endif
</div>

{{-- Remarks --}}
<div class="form-group">
	<label for="details">Remarks</label>
	<textarea name="details" class="form-control {{ $errors->has('details') ? ' is-invalid' : '' }}" id="details" cols="30" rows="5">{{ old('details', optional($ccLoanDeposit)->details) }}</textarea>

	@if ($errors->has('details'))
	<span class="invalid-feedback">
		<strong>{{ $errors->first('details') }}</strong>
	</span>
	@endif
</div>

{{-- Save --}}
<div class="form-group row mb-0">
	<div class="col-md-12">
		<button type="submit" class="btn btn-primary">
			{{ __('Save') }}
		</button>
	</div>
</div>

@section('script')
<script>
	{{-- jquery datepicker --}}
	$( function() {
		$( "#withdraw_date" ).datepicker({
			dateFormat: 'yy-mm-dd',
			changeMonth: true,
			changeYear: true,
			onSelect: showDays
		});

		$( "#deposit_date" ).datepicker({
			dateFormat: 'yy-mm-dd',
			changeMonth: true,
			changeYear: true,
			onSelect: showDays
		});

		var withdraw_date=$("#withdraw_date");
		var deposit_date=$("#deposit_date");
		var interest_rate=$("#interest_rate");
		var amount=$("#amount");

		function parseDate(str) {
		    var mdy = str.split('-');
		    return new Date(mdy);
		}

		function datediff(first, second) {
		    // Take the difference between the dates and divide by milliseconds per day.
		    // Round to nearest whole number to deal with DST.
		    return Math.round((second-first)/(1000*60*60*24));
		}

		function showDays() {
		    var days = (datediff(parseDate(withdraw_date.val()), parseDate(deposit_date.val())));
			//console.log(days);
			var interest = isNaN(parseFloat(((((interest_rate.val() * amount.val())/10)/365) *days))) ? 0 :((((interest_rate.val() * amount.val())/10)/365) *days);
			$("#interest").val(interest);
		}

		interest_rate.keyup(showDays);
		amount.keyup(showDays);
	});
</script>
@endsection

resources/views/pages/cc-loan-deposit/index.blade.php
@extends('layouts.master')
@section('title', 'CC Loan')

@section('content')
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Deposits</h1>
				</div><!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
						<li class="breadcrumb-item active">Loan Deposit</li>
					</ol>
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="card">
				<div class="card-header">
					{{-- <a href="{{ url('loan/print') }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Print" target="_blank">
						<i class="fa fa-print" aria-hidden="true" title="Print"></i> Print
					</a>

					<a href="{{ url('loan/pdf') }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="PDF" target="_blank">
						<i class="fa fa-file-pdf-o" aria-hidden="true" title="PDF"></i> PDF
					</a>

					<a href="{{ url('loan/excel') }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Excel" target="_blank">
						<i class="fa fa-file-excel-o" aria-hidden="true" title="Excel"></i> Excel
					</a> --}}
				</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
							<thead>
								<tr>
									<th>Sl</th>
									<th>Loan</th>
									<th>Deposit Date</th>
									<th>Withdraw Date</th>
									<th>Amount</th>
									<th>Profit</th>
									<th>Remarks</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@forelse($deposits as $deposit)
								<tr>
									<td>{{ $loop->iteration }}</td>
									<td>{{ $deposit->loan->loan_from }}</td>
									<td>{{ $deposit->deposit_date->format("d-m-Y") }}</td>
									<td>{{ $deposit->withdraw_date->format("d-m-Y") }}</td>
									<td>{{ $deposit->amount }}</td>
									<td>{{ $deposit->interest }}</td>
									<td>{{ $deposit->details }}</td>
									<td>
										<div class="btn-group">
											<a href="{{ route('cc-loan-deposit.edit', $deposit->id) }}" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Update">
												Update
											</a>
											<form action="{{ route('cc-loan-deposit.destroy', $deposit->id) }}" method="POST">
												@csrf
												@method('DELETE')
												<button class="btn btn-danger btn-sm">Delete</button>
											</form>
										</div>
									</td>
								</tr>
								@empty
								@endforelse
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

@endsection

@section('script')
<script>
	//server side data table
	$(document).ready(function () {
		$('#dataTable').DataTable();
	});
</script>
@endsection